name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - master
  schedule:
      # 国际标准时间 16 17 18 19 20 21 22 23  0  1  2  3  4  5  6  6  8  9 10 11 12 13 14 15
      # 北京时间      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
    - cron: '5 16,22 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SERVERCHAN_SCKEY: ${{ secrets.SERVERCHAN_SCKEY }}
        run: python main.py
